spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_app
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hbm2ddl:
          auto: create
      jakarta:
        persistence:
          sql-load-script-source: META-INF/import.sql
