spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate  # Safer default for production
      jakarta:
        persistence:
          sql-load-script-source: META-INF/import.sql
