spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_app
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: GymAppHikariPool-Dev
      auto-commit: true
      connection-timeout: 30000
      max-lifetime: 1800000
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create  # Update schema for development
        show_sql: true
server:
  port: 8080